name: Build and deploy React (Vite) app to Azure Web App - unac-meli-front

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # 🔥 ZIP BIEN HECHO (sin carpeta dist)
      - name: Create deployment package
        run: |
          rm -f site.zip
          cd dist
          zip -r ../site.zip *
          cd ..

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DE4A8522E98147F5BC074B1A2EE0E559 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9281BDB3321C45E0B770601155A6251E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D990230CF0BE48EDB46238E541776361 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: unac-meli-front
          slot-name: Production
          package: site.zip
